apiVersion: v1
kind: Service
metadata:
  name: service-versioner
  namespace: xylon
  labels:
    component: ClusterIP
spec:
  type: ClusterIP
  selector:
    microservice: versioner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
