name: CI - Quality Gates & Build Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/build.yml'
      - '.github/workflows/deploy.yml'

jobs:
  Continuous_Integration_CI:
    name: Continuous_Integration_CI - ${{ github.event.repository.name }}
    uses: .github/workflows/template_ci.yml@main
    with:
      api_name: ${{ github.event.repository.name }}

  Continuous_Deployment_CD:
    name: Continuous_Deployment_CD - ${{ github.event.repository.name }}
    needs: Continuous_Integration_CI
    if: github.ref == 'refs/heads/main'
    uses: .github/workflows/template_cd.yml@main
    with:
      api_name: ${{ github.event.repository.name }}