name: CI/CD - Quality Gates & Build Docker Image & Deploy to Kubernetes

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'

jobs:
  Continuous_Integration_CI:
    name: Continuous_Integration_CI - ${{ github.event.repository.name }}
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/template_ci.yml
    with:
      api_name: ${{ github.event.repository.name }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  Continuous_Deployment_CD:
    name: Continuous_Deployment_CD - ${{ github.event.repository.name }}
    needs: Continuous_Integration_CI
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/template_cd.yml
    with:
      api_name: ${{ github.event.repository.name }}