name: CD - Deploy Resources to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Quality Gates & Build Docker Image"] # Debe coincidir EXACTAMENTE
    types:
      - completed

env:
  API_NAME: versioner
  API_LOG_LEVEL: short
  PORT: 3000
  NAME_SPACE: ${{ vars.NAME_SPACE }}

jobs:
  deploy_to_kubernetes:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to Kubernetes ${{ github.event.repository.name }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Deploy to Service
        run: kubectl apply -f kubernetes/01-Service.yml
      - name: Deploy to Deployment
        run: kubectl apply -f kubernetes/01-Service.yml
      - name: Restart Deployments
        run: kubectl -n xylon rollout restart deployment ${{ github.event.repository.name }}
      - name: Check Deployment node-chat
        run: kubectl -n xylon rollout status deployment ${{ github.event.repository.name }}
